In [1]:
# Import functions from the modules
from modules.data_preparation import process_dataset_testing, process_dataset_training, authenticate_kaggle,  download_dataset
from modules.model import build_model, load_model
from modules.training import train_model, train_model_k_fold
from modules.visualization import visualize_results
from modules.test import evaluate_model_on_test_set, evaluate_model_on_test_set_w_confusion

In [2]:
import torch
import os
from sklearn.metrics import confusion_matrix

In [3]:
dataset_name = "aniruddhsharma/structural-defects-network-concrete-crack-images"
dataset_name = "imtkaggleteam/concrete-crack-classification"
dataset_dir = "data/D4"

In [4]:
# Download the dataset
authenticate_kaggle()
download_dataset(dataset_name, dataset_dir)

Dataset URL: https://www.kaggle.com/datasets/imtkaggleteam/concrete-crack-classification


In [4]:
# Build the model based on trained parameters from D1
model_paths = ['CNN_models/D1_params.pt', 'CNN_models/D2.pt', 'CNN_models/D1_D2.pt']
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model, criterion, optimizer, exp_lr_scheduler = build_model()


In [5]:
for model in model_paths:
    print(f'Model: {model}')
    model = load_model(model, device)
    dataloader, class_names = process_dataset_testing(dataset_dir, subset_fraction=1)
    accuracy, precision, recall, f1, all_labels, all_preds = evaluate_model_on_test_set(model, dataloader, device)
    cm = confusion_matrix(all_labels, all_preds)
    print(cm)
    # for concrete_structure in os.listdir(dataset_dir):
    #     print(f'- Structure: {concrete_structure}')
    #     folder_path = os.path.join(dataset_dir, concrete_structure)
    #     dataloader, class_names = process_dataset_testing(folder_path, subset_fraction=1)
    #     accuracy, precision, recall, f1, all_labels, all_preds = evaluate_model_on_test_set(model, dataloader, device)
    #     cm = confusion_matrix(all_labels, all_preds)
    #     print(cm)

Model: CNN_models/D1_params.pt
Test Accuracy: 0.9962
Test Precision: 0.9962
Test Recall: 0.9962
Test F1-Score: 0.9962
[[19944    56]
 [   97 19903]]
Model: CNN_models/D2.pt
Test Accuracy: 0.9138
Test Precision: 0.9241
Test Recall: 0.9138
Test F1-Score: 0.9132
[[16716  3284]
 [  165 19835]]
Model: CNN_models/D1_D2.pt
Test Accuracy: 0.8799
Test Precision: 0.9020
Test Recall: 0.8799
Test F1-Score: 0.8782
[[15254  4746]
 [   58 19942]]


array([[200,  50],
       [ 50, 200]])