In [1]:
# Import functions from the modules
from modules.data_preparation import process_dataset_testing, process_dataset_training, authenticate_kaggle,  download_dataset
from modules.model import build_model, load_model
from modules.training import train_model, train_model_k_fold
from modules.visualization import visualize_results
from modules.test import evaluate_model_on_test_set, evaluate_model_on_test_set_w_confusion

In [2]:
import torch
import os
from sklearn.metrics import confusion_matrix

In [3]:
dataset_name = "aniruddhsharma/structural-defects-network-concrete-crack-images"
dataset_dir = "data/D3"

In [ ]:
# Download the dataset
authenticate_kaggle()
download_dataset(dataset_name, dataset_dir)

Dataset URL: https://www.kaggle.com/datasets/aniruddhsharma/structural-defects-network-concrete-crack-images


In [7]:
# Build the model based on trained parameters from D1
model_paths = ['CNN_models/D1_params.pt', 'CNN_models/D1_D2.pt']
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model, criterion, optimizer, exp_lr_scheduler = build_model()


In [8]:
for model in model_paths:
    print(f'Model: {model}')
    model = load_model(model, device)
    for concrete_structure in os.listdir(dataset_dir):
        print(f'- Structure: {concrete_structure}')
        folder_path = os.path.join(dataset_dir, concrete_structure)
        dataloader, class_names = process_dataset_testing(folder_path, subset_fraction=1)
        accuracy, precision, recall, f1, all_labels, all_preds = evaluate_model_on_test_set(model, dataloader, device)
        cm = confusion_matrix(all_labels, all_preds)
        print(cm)

Model: CNN_models/D1_params.pt
- Structure: Walls
Test Accuracy: 0.2552
Test Precision: 0.5772
Test Recall: 0.2552
Test F1-Score: 0.2085
[[ 3157   694]
 [12816  1471]]
- Structure: Pavements
Test Accuracy: 0.4178
Test Precision: 0.7487
Test Recall: 0.4178
Test F1-Score: 0.5204
[[  697  1911]
 [12256  9470]]
- Structure: Decks
Test Accuracy: 0.1880
Test Precision: 0.6438
Test Recall: 0.1880
Test F1-Score: 0.1481
[[ 1716   309]
 [10750   845]]
Model: CNN_models/D1_D2.pt
- Structure: Walls
Test Accuracy: 0.4735
Test Precision: 0.6434
Test Recall: 0.4735
Test F1-Score: 0.5208
[[1757 2094]
 [7455 6832]]
- Structure: Pavements
Test Accuracy: 0.2130
Test Precision: 0.6702
Test Recall: 0.2130
Test F1-Score: 0.2725
[[ 1244  1364]
 [17787  3939]]
- Structure: Decks
Test Accuracy: 0.2412
Test Precision: 0.6526
Test Recall: 0.2412
Test F1-Score: 0.2614
[[1369  656]
 [9679 1916]]


array([[200,  50],
       [ 50, 200]])